import pygame

# SCREEN SIZE 
SCREEN_WIDTH, SCREEN_HEIGHT = 600, 600

# BOARD SIZE
ROWS, COLUMNS = 8, 8

# SIZE OF SQUARES ON BOARD
SQUARE_SIZE = SCREEN_WIDTH//COLUMNS

# RGB COLORS ON BOARD
GREEN = (0, 255, 0)
WHITE = (255, 255, 255)
BLACK = (0, 0, 0)